// "use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { AppSidebar } from "./Components/Sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { SearchBar } from "./Components/Search";
import { SearchProvider } from "./context/SearchContext";

import "./globals.css";

// Usikker på hva som skal faktisk være typer i denne interfacen..
type RootLayoutProps = {
  children: React.ReactNode;
};


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className="flex flex-col h-screen">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-1">
            <SidebarProvider>
              <AppSidebar /> {/* Sidebar på venstre side */}
              <SearchProvider>
                <div className="flex flex-col flex-1 p-1">
                  <div className="flex">
                    <SidebarTrigger className="p-4" /> {/* Sidebar-knapp */}
                    <SearchBar />
                  </div>
                  <main>{children}</main>
                </div>
              </SearchProvider>
            </SidebarProvider>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}

