import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { AppSidebar } from "./Components/Sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Usikker på hva som skal faktisk være typer i denne interfacen..
type RootLayoutProps = {
  children: React.ReactNode;
};


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className="flex flex-col h-screen">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* Navbar plasseres øverst uavhengig av sidebaren */}
          {/* <NavigationBar /> */}

          <div className="flex flex-1">
            <SidebarProvider>
              <AppSidebar /> {/* Sidebar på venstre side */}
              <div className="flex flex-col flex-1 p-4">
                <SidebarTrigger className="p-4" /> {/* Sidebar-knapp */}
                <main>{children}</main>
              </div>
            </SidebarProvider>
          </div>

        </ThemeProvider>
      </body>
    </html>
  );
}

