// "use client";
import type { Metadata } from "next";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { AppSidebar } from "./Components/Sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { SearchBar } from "./Components/Search";
import { SearchProvider } from "./context/SearchContext";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";

// Usikker på hva som skal faktisk være typer i denne interfacen..
type RootLayoutProps = {
  children: React.ReactNode;
};
 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className="h-screen overflow-hidden"> {/* Endre dette */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <div className="flex h-full"> {/* Endre dette */}
              <AppSidebar />
              <SearchProvider>
                <div className="flex flex-col flex-1 overflow-hidden"> {/* Legg til overflow-hidden */}
                  <div className="flex items-center p-1"> {/* Legg til items-center */}
                    <SidebarTrigger className="p-4" />
                    <SearchBar />
                  </div>
                  <main className="flex-1 overflow-auto p-1"> {/* Legg til overflow-auto */}
                    {children}
                  </main>
                </div>
              </SearchProvider>
            </div>
          </SidebarProvider>
        </ThemeProvider>
        <Toaster position="bottom-right"></Toaster>
      </body>
    </html>
  );
}

